# Generated by Django 4.0.4 on 2022-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='company_email',
            field=models.EmailField(max_length=60),
        ),
    ]
